---
# MySQL
- name: Install MySQL
  apt: name={{item}} state=installed
  with_items:
    - mysql-server-5.6
    - python-mysqldb
- name: Start MySQL
  service: name=mysql state=started

# Remove MySQL default security problems
- name: Generate a new root password
  command: openssl rand -hex 7 creates=/root/.my.cnf
  register: mysql_new_root_pass
- name: Remove anonymous users
  mysql_user: name="" state=absent
  when: mysql_new_root_pass.changed
- name: Remove test database
  mysql_db: name=test state=absent
  when: mysql_new_root_pass.changed
- name: Update root password
  mysql_user: name=root host={{item}}
    password={{mysql_new_root_pass.stdout}}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: mysql_new_root_pass.changed
- name: Output new root password
  debug:
    msg: "New root password is {{mysql_new_root_pass.stdout}}"
  when: mysql_new_root_pass.changed
- name: Create my.cnf
  template:
    src: my.cnf
    dest: /root/.my.cnf
  when: mysql_new_root_pass.changed
