---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: ubuntu/trusty64
    # box: ubuntu/xenial64
    memory: 1024
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        blogs:
          - name: "wp1"
            username: admin
            password: admin
          - name: "wp2"
            username: admin
            password: admin
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
